import { useEffect, useMemo, useRef, useState } from 'react'
import DOMPurify from 'dompurify'
import { marked } from 'marked'
import type { MimeBundle, MimeMetadata } from '../pyodide/types'
import { CRIBL_SEARCH_MIME, type CriblSearchPayload } from '../pyodide/types'
import { CriblSearchOutputView } from './CriblSearchOutput'
import { PlotlyMimeView } from './PlotlyMimeView'
import { VegaMimeView } from './VegaMimeView'
import { pickRenderer, registerMimeRenderer } from './mimeRegistry'

const SCRIPT_RE = /<script[\s>]/i

/**
 * Renders HTML that contains <script> tags inside a sandboxed srcdoc iframe.
 *
 * DOMPurify strips scripts from inline HTML, which breaks outputs from
 * libraries like itables/DataTables that rely on inline JS to initialise.
 * Placing the HTML in an iframe srcdoc keeps scripts intact. The sandbox
 * uses `allow-same-origin` so that cross-cell globals (e.g. the DataTables
 * blob URL that itables stores in `window._itables_*`) can be shared between
 * frames via the parent window. The inherit/export shims below copy those
 * globals at frame startup and after load, so `show(df)` works even when
 * `init_notebook_mode()` ran in an earlier cell's frame.
 *
 * Auto-sizing: the injected resize script posts the document scroll-height
 * back to the parent via postMessage so the iframe height tracks its content.
 *
 * Security note: `allow-same-origin` lets iframe scripts access window.parent.
 * In a notebook where users run their own Python, the output scripts are
 * generated by user code, so this is the same trust level as the rest of
 * the kernel execution.
 */
function ScriptedHtmlMime({ data }: { data: string }) {
  const frameId = useRef(`nb_iframe_${Math.random().toString(36).slice(2)}`)
  const [height, setHeight] = useState(300)

  const srcdoc = useMemo(() => {
    const id = frameId.current

    // Inherit any cross-cell globals (e.g. itables blob URLs) from the parent
    // window before the frame's own scripts run. This ensures that a `show(df)`
    // frame can find `window._itables_2_7_3` even if `init_notebook_mode()`
    // ran in a different frame.
    const inheritScript =
      `<script>(function(){try{var p=window.parent;` +
      `Object.getOwnPropertyNames(p).forEach(function(k){` +
      `if(/^_itables_/.test(k))try{window[k]=p[k];}catch(e){}` +
      `});}catch(e){}})();<\/script>`

    // After the frame finishes loading, export any globals that this frame set
    // (e.g. the DataTables blob URL created by `init_notebook_mode()`) back to
    // the parent so that subsequent frames can inherit them.
    const exportAndResizeScript =
      `<script>(function(){` +
      `var _id='${id}';` +
      `function _export(){try{var p=window.parent;` +
      `Object.getOwnPropertyNames(window).forEach(function(k){` +
      `if(/^_itables_/.test(k))try{p[k]=window[k];}catch(e){}` +
      `});}catch(e){}}` +
      `function _sz(){` +
      `_export();` +
      `try{window.parent.postMessage({type:'nb-iframe-resize',id:_id,` +
      `h:Math.max(document.documentElement.scrollHeight,document.body.scrollHeight)` +
      `},'*');}catch(e){}}` +
      `window.addEventListener('load',function(){setTimeout(_sz,150);});` +
      `var _b=document.body;if(_b)new MutationObserver(function(){setTimeout(_sz,80);})` +
      `.observe(_b,{childList:true,subtree:true,attributes:true});` +
      `})()</` +
      `script>`

    return inheritScript + data + exportAndResizeScript
  }, [data])

  useEffect(() => {
    const id = frameId.current
    function onMsg(e: MessageEvent) {
      if (e.data?.type === 'nb-iframe-resize' && e.data?.id === id) {
        setHeight((prev) => Math.max(prev, (e.data.h as number) + 24))
      }
    }
    window.addEventListener('message', onMsg)
    return () => window.removeEventListener('message', onMsg)
  }, [])

  // Reset height when cell output is replaced (data changes).
  useEffect(() => {
    setHeight(300)
  }, [data])

  return (
    <iframe
      srcDoc={srcdoc}
      sandbox="allow-scripts allow-same-origin"
      className="nb-mime-html-iframe"
      style={{ width: '100%', height: `${height}px`, border: 'none', display: 'block' }}
      title="cell output"
    />
  )
}

function HtmlMime({ data }: { data: string }) {
  if (SCRIPT_RE.test(data)) return <ScriptedHtmlMime data={data} />
  const safe = useMemo(
    () =>
      DOMPurify.sanitize(data, {
        ADD_TAGS: ['iframe'],
        ADD_ATTR: ['allow', 'allowfullscreen', 'frameborder', 'scrolling', 'srcdoc', 'sandbox'],
        FORBID_TAGS: ['script'],
      }),
    [data],
  )
  return <div className="nb-mime-html" dangerouslySetInnerHTML={{ __html: safe }} />
}

function SvgMime({ data }: { data: string }) {
  const safe = useMemo(
    () => DOMPurify.sanitize(data, { USE_PROFILES: { svg: true, svgFilters: true } }),
    [data],
  )
  return <div className="nb-mime-svg" dangerouslySetInnerHTML={{ __html: safe }} />
}

function ImageMime({ data, mime }: { data: string; mime: string }) {
  return (
    <img
      className="nb-mime-image"
      src={`data:${mime};base64,${data.replace(/\s+/g, '')}`}
      alt=""
    />
  )
}

function MarkdownMime({ data }: { data: string }) {
  const html = useMemo(() => {
    const rendered = marked.parse(data, { async: false }) as string
    return DOMPurify.sanitize(rendered, {
      ADD_TAGS: ['iframe'],
      FORBID_TAGS: ['script'],
    })
  }, [data])
  return <div className="nb-mime-markdown" dangerouslySetInnerHTML={{ __html: html }} />
}

function JsonMime({ data }: { data: string }) {
  const pretty = useMemo(() => {
    try {
      return JSON.stringify(JSON.parse(data), null, 2)
    } catch {
      return data
    }
  }, [data])
  return <pre className="nb-output-pre nb-mime-json">{pretty}</pre>
}

function PlainMime({ data }: { data: string }) {
  return <pre className="nb-output-pre">{data}</pre>
}

function CriblSearchMime({ data }: { data: string }) {
  const payload = useMemo((): CriblSearchPayload | null => {
    try {
      const p = JSON.parse(data) as CriblSearchPayload
      if (p && (p.kind === 'running' || p.kind === 'completed' || p.kind === 'failed')) {
        return p
      }
    } catch {
      // fallthrough
    }
    return null
  }, [data])
  if (!payload) return <PlainMime data={data} />
  return <CriblSearchOutputView payload={payload} />
}

function WidgetFallback() {
  return (
    <pre className="nb-output-pre nb-mime-widget-fallback">
      [Jupyter widget — interactive rendering not yet implemented]
    </pre>
  )
}

let registered = false
function ensureRegistered() {
  if (registered) return
  registered = true
  registerMimeRenderer({
    mime: CRIBL_SEARCH_MIME,
    rank: 100,
    render: (data) => <CriblSearchMime data={data} />,
  })
  registerMimeRenderer({
    mime: 'application/vnd.jupyter.widget-view+json',
    rank: 90,
    render: () => <WidgetFallback />,
  })
  /*
   * Plotly + Vega must rank above the Jupyter widget stub (90). Otherwise a
   * bundle that includes both real chart MIME and ipywidgets placeholder keys
   * loses the chart to “[Jupyter widget — interactive rendering not yet implemented]”.
   */
  registerMimeRenderer({
    mime: 'application/vnd.plotly.v1+json',
    rank: 96,
    render: (plotlyData) => <PlotlyMimeView key={plotlyData} data={plotlyData} />,
  })
  /** Vega-Lite 5/6 (+json and Altair’s historic “.json” suffix). */
  for (const mime of [
    'application/vnd.vegalite.v5+json',
    'application/vnd.vegalite.v6+json',
    'application/vnd.vegalite.v6.json',
  ] as const) {
    registerMimeRenderer({
      mime,
      rank: 95,
      render: (spec) => <VegaMimeView key={spec} data={spec} />,
    })
  }
  /** Vega 5/6 (Vega-Lite is preferred when both appear). */
  for (const mime of [
    'application/vnd.vega.v5+json',
    'application/vnd.vega.v6+json',
    'application/vnd.vega.v6.json',
  ] as const) {
    registerMimeRenderer({
      mime,
      rank: 94,
      render: (spec) => <VegaMimeView key={spec} data={spec} />,
    })
  }
  registerMimeRenderer({
    mime: 'text/html',
    rank: 80,
    render: (data) => <HtmlMime data={data} />,
  })
  registerMimeRenderer({
    mime: 'image/svg+xml',
    rank: 75,
    render: (data) => <SvgMime data={data} />,
  })
  registerMimeRenderer({
    mime: 'image/png',
    rank: 70,
    render: (data) => <ImageMime data={data} mime="image/png" />,
  })
  registerMimeRenderer({
    mime: 'image/jpeg',
    rank: 70,
    render: (data) => <ImageMime data={data} mime="image/jpeg" />,
  })
  registerMimeRenderer({
    mime: 'text/markdown',
    rank: 60,
    render: (data) => <MarkdownMime data={data} />,
  })
  registerMimeRenderer({
    mime: 'application/json',
    rank: 50,
    render: (data) => <JsonMime data={data} />,
  })
  registerMimeRenderer({
    mime: 'text/plain',
    rank: 0,
    render: (data) => <PlainMime data={data} />,
  })
}
ensureRegistered()

export function MimeBundleView({
  data,
  metadata,
}: {
  data: MimeBundle
  metadata: MimeMetadata
}) {
  const renderer = pickRenderer(data)
  if (renderer) {
    const value = data[renderer.mime]
    if (typeof value === 'string') return <>{renderer.render(value, metadata)}</>
  }
  const tp = data['text/plain']
  return <PlainMime data={typeof tp === 'string' ? tp : ''} />
}
